# Generated by Django 4.1.1 on 2022-10-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_remove_order_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
