# Generated by Django 4.1.1 on 2022-10-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_delete_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
