# Generated by Django 4.1.1 on 2022-10-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
