# Generated by Django 4.1.1 on 2022-10-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_rename_product_id_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
