# Generated by Django 4.1.1 on 2022-10-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_rename_product_order_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
