# Generated by Django 4.1.1 on 2022-09-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_desc', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductToolsUsed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('figma', models.BooleanField(default=True)),
                ('photoshop', models.BooleanField(default=True)),
                ('illustrator', models.BooleanField(default=False)),
                ('invision', models.BooleanField(default=False)),
                ('figjam', models.BooleanField(default=False)),
                ('html', models.BooleanField(default=False)),
                ('css', models.BooleanField(default=False)),
                ('js', models.BooleanField(default=False)),
                ('sass', models.BooleanField(default=False)),
                ('axios', models.BooleanField(default=False)),
                ('react', models.BooleanField(default=True)),
                ('tailwind', models.BooleanField(default=True)),
                ('vite', models.BooleanField(default=False)),
                ('nextjs', models.BooleanField(default=False)),
                ('typescript', models.BooleanField(default=False)),
                ('django', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='details_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.productdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tools',
            field=models.ManyToManyField(to='Product.producttoolsused'),
        ),
    ]
