# Generated by Django 4.1.1 on 2022-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productdetail_producttoolsused_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttoolsused',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
