# Generated by Django 4.1.1 on 2022-09-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_category_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apps', 'Apps'), ('templates', 'Templates'), ('courses', 'Courses')], default='', max_length=255),
        ),
    ]
