# Generated by Django 4.1.1 on 2022-09-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_producttoolsused_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttoolsused',
            name='name',
        ),
        migrations.AddField(
            model_name='producttoolsused',
            name='figjam_img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttoolsused',
            name='figma_img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttoolsused',
            name='illustrator_img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttoolsused',
            name='invision_img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttoolsused',
            name='photoshop_img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.ManyToManyField(to='Product.producttoolsused')),
            ],
        ),
    ]
