# Generated by Django 4.1.1 on 2022-09-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_delete_category_remove_product_category_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_id',
            new_name='discount',
        ),
    ]
