# Generated by Django 4.1.1 on 2022-09-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_producttoolsused_figjam_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttoolsused',
            name='figjam_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producttoolsused',
            name='figma_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producttoolsused',
            name='illustrator_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producttoolsused',
            name='invision_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producttoolsused',
            name='photoshop_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
