# Generated by Django 4.1.1 on 2022-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_producttoolsused_figjam_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttoolsused',
            name='name',
            field=models.CharField(default='Figma', max_length=255),
            preserve_default=False,
        ),
    ]
