# Generated by Django 4.1.1 on 2022-09-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_producttoolsused_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTool',
        ),
    ]
