# Generated by Django 4.1.1 on 2022-09-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_rename_figjam_img_producttoolsused_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttoolsused',
            name='django',
        ),
    ]
