# Generated by Django 4.1.1 on 2022-09-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_remove_producttoolsused_django'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttoolsused',
            name='axios',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='css',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='figjam',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='figma',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='html',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='illustrator',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='invision',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='js',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='nextjs',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='photoshop',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='react',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='sass',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='tailwind',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='typescript',
        ),
        migrations.RemoveField(
            model_name='producttoolsused',
            name='vite',
        ),
        migrations.AddField(
            model_name='producttoolsused',
            name='tool',
            field=models.CharField(choices=[('figma', 'Figma'), ('photoshop', 'Photoshop'), ('illustrator', 'Illustrator'), ('invision', 'Invision'), ('figjam', 'Figjam'), ('html', 'Html'), ('css', 'Css'), ('js', 'Js'), ('sass', 'Sass'), ('axios', 'Axios'), ('react', 'React'), ('tailwind', 'Tailwind'), ('vite', 'Vite'), ('nextjs', 'Nextjs'), ('typescript', 'Typescript'), ('django', 'Django')], default='', max_length=255),
        ),
    ]
