# Generated by Django 4.1.1 on 2022-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_alter_producttoolsused_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='syf',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
