# Generated by Django 4.1.1 on 2022-09-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_product_syf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='syf',
        ),
    ]
