# Generated by Django 4.1.1 on 2022-09-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_productdetail_image1_productdetail_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
