# Generated by Django 4.1.1 on 2022-10-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_producttoolsused_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apps', 'Apps'), ('templates', 'Templates'), ('courses', 'Courses')], max_length=255),
        ),
        migrations.AlterField(
            model_name='producttoolsused',
            name='tool',
            field=models.CharField(choices=[('Figma', 'Figma'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('Invision', 'Invision'), ('Figjam', 'Figjam'), ('Html', 'Html'), ('Css', 'Css'), ('Js', 'Js'), ('Sass', 'Sass'), ('Axios', 'Axios'), ('React', 'React'), ('Tailwind', 'Tailwind'), ('Vite', 'Vite'), ('Nextjs', 'Nextjs'), ('Typescript', 'Typescript'), ('Django', 'Django'), ('Postgresql', 'Postgresql')], max_length=255),
        ),
    ]
