# Generated by Django 4.1.1 on 2022-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_alter_producttoolsused_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttoolsused',
            name='tool',
            field=models.CharField(choices=[('Figma', 'Figma'), ('Adobe Photoshop', 'Adobe Photoshop'), ('Adobe Illustrator', 'Adobe Illustrator'), ('InVision', 'InVision'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('Sass', 'Sass'), ('React', 'React'), ('Tailwind CSS', 'Tailwind CSS'), ('Vite', 'Vite'), ('NextJs', 'NextJs'), ('TypeScript', 'TypeScript'), ('Django', 'Django'), ('JSON Web Token', 'JSON Web Token'), ('PostgreSQL', 'PostgreSQL')], max_length=255),
        ),
    ]
