# Generated by Django 4.1.1 on 2022-10-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_alter_producttoolsused_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='details_id',
            new_name='details',
        ),
    ]
