# Generated by Django 4.1.1 on 2022-10-18 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_alter_product_details_delete_product2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productdetail'),
        ),
    ]
