# Generated by Django 4.1.1 on 2022-10-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_product_slug_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
