# Generated by Django 4.1.1 on 2022-10-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
